# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
