# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0002_auto_20170512_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokers',
            name='poke',
        ),
        migrations.RemoveField(
            model_name='pokes',
            name='poke_by',
        ),
        migrations.RemoveField(
            model_name='pokes',
            name='user',
        ),
        migrations.DeleteModel(
            name='Pokers',
        ),
        migrations.DeleteModel(
            name='Pokes',
        ),
    ]
