# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0003_auto_20170513_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
